version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production RAILS_SERVE_STATIC_FILES=true bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/app