version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: 2.4.4-jessie-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3
          npm install
      - run:
        name: run tests
        command: |
          rails test